version: "3"
services:
  postgres:
    build: git@github.com:ruudschiphorst/stempol_postgres.git
    image: politie/postgres
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASS}"
      POSTGRES_DB: stempol_notes
      POSTGRES_HOST_AUTH_METHOD: "trust"
  auth_api:
    build: git@github.com:ruudschiphorst/stempol_auth_api.git
    image: politie/auth_api
    ports: ["8085:8085"]
    environment:
      KEYSTORE_PASS: "${KEYSTORE_PASS}"
      JWT_SIGNING_KEY: "${JWT_SIGNING_KEY}"
  db_api:
    build: git@github.com:ruudschiphorst/stempol_db_api.git
    image: politie/db_api
    ports: ["8086:8086"]
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASS}"
      KEYSTORE_PASS: "${KEYSTORE_PASS}"
      JWT_SIGNING_KEY: "${JWT_SIGNING_KEY}"
    depends_on:
      - postgres
volumes:
  postgres_volume:

